spring.application.name=workout-tracker

spring.datasource.url=jdbc:mysql://localhost:3306/workout-tracker
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Port de l'API
server.port=8080

spring.profiles.active=local